sudo: required
language: go
notifications:
  email: false

go:
- 1.10.x

script:
- dpkg-buildpackage -us -uc -b

install:
- sudo apt update && sudo apt install -yq golang-go binutils dpkg-dev build-essential fakeroot debhelper

deploy:
  provider: releases
  api_key:
    secure: 0NTDlyB2M6FScistFIY/uK2ueFYRtVelbuCoj1JPDIbNNwykh6xk1sFOSHi9rtfUtjwb7jH+HxjsRWyiUMJQoh7/EQHYHvdMeiNsWDW+kzGE6bKRUH+d9Z399HgusAD/SvfgDAJ4GrACswI1DF6wC1QlqFG03cjII0nUG7IQOaLmENP7oGWZeFWHtRy8cS716Tp8hQ2AT8o4Jr9oP3ekDaED3ipIICQV/jDTxPoD3HBqUgI4LJ7+Z6ByPgQsTlZGi6QpxZkFcwOKXJHqo/BQkxsGMHRreyHLUoDE4HaoKoa3cVfv0RLyyuDdDjVCZBDSvPADvPeawX+FjNWzmXDVKQ1lDBa/9alMQ79lWc6tViRUHz4szSb/KujjUVSoiQLfMw6qg1dItsJHHJ1Nke5Rx2k9NSb90iVsPUDcEosZoT5kLi97kakq5bumSkiuUjblpWMjsEBp/hERlc0DjzsF8ypT/wXuSXPvclcjfrEDt3bzAOoTtJNnkEItqQP0hbtiVD+QMyRS7mnFk48zi5SD599AnjKaRr6acOTe2XIoy0vG4+xQ272/nG23qX78ZaxfGME5A1QFYLkW0tCt7JIhuO7Q7kNtigZBIMS6E+5OqLuntOhWlw/T3kOsIs3GqOgX0sZw1KRv6zMOut/Zm25oo26xcZzy1+LqIReCm4s9lmE=
  file_glob: true
  file: "../etcd-server*.deb"
  on:
    repo: vs-eth/etcd
    tags: true
